# Use root/example as user/password credentials
# Although the mysql_native_password authentication method has known vulnerabilities (https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions),
##  prisma client does not currently work with the sha256_password or caching_sha256_password currently.
##  https://github.com/prisma/prisma/issues/9454 https://github.com/prisma/prisma/discussions/14181 https://github.com/prisma/prisma/discussions/14181#discussioncomment-3186342
version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3306:3306"
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  # opencms:
  #   image: open-crm
  #   ports:
  #   - "3000:80"
  #   environment:
  #     MYSQL_SERVER: localhost
  #     MYSQL_USER: youruser
  #     MYSQL_PASSWORD: yourpassword
  #     MYSQL_DATABASE: open-crm
