# Use root/example as user/password credentials
version: "3.1"
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_USER: youruser
            MYSQL_PASSWORD: yourpassword
    # opencrm:
    #   image: open-crm
    #   ports:
    #   - "3000:80"
    #   environment:
    #     MYSQL_USER: youruser
    #     MYSQL_PASSWORD: yourpassword
